apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-engine
spec:
  selector:
    matchLabels:
      app: nlp-engine
  template:
    metadata:
      labels:
        app: nlp-engine
    spec:
      containers:
      - name: nlp-engine
        image: gcr.io/power-project-eda/nlp-engine:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          volumeMounts:
            - mountPath: /var/secrets/google
              name: eda-secrets
          env:
            - name: REDIS_HOST
              value: redis:6379
            - name: MYSQL_HOST
              value: mysql:3306
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
      restartPolicy: Always
      volumes:
        - name: eda-secrets
          secret:
            secretName: eda-secrets

